In [ ]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install statsmodels

Requirement already satisfied: statsmodels in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (2.4.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.17.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (3.0.0)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [ ]:
!pip install statsmodels

Requirement already satisfied: statsmodels in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (2.4.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.17.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (3.0.0)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ztest

In [8]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ztest
from scipy.stats import skew, f_oneway, pearsonr, ttest_rel,chi2_contingency, spearmanr
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ztest

print("Everything imported successfully!")

Everything imported successfully!

In [6]:
import pandas as pd
print(pd.__version__)

3.0.0

In [12]:
file_path = r"C:\Users\PC\Documents\DS_Statistics_Project\Tampa 100 Video.xlsx"

data_2024 = pd.read_excel(file_path, sheet_name="2024")
data_2023 = pd.read_excel(file_path, sheet_name="2023")

In [13]:
data_2024.head(10)

,Place,First_Name,Last_Name,City,State,Age,Gender,Time
0,1,Lucas,Vidal,Cape Coral,FL,38,M,19:43:00
1,2,Brandon,Westover,Orlando,FL,45,M,21:15:00
2,3,Lucas,Hathaway,Atlanta,GA,34,M,23:31:36
3,4,Sage,Lyons,Sarasota,FL,27,F,23:37:05
4,5,Colin,Gotham,Land O Lakes,FL,30,M,"1 day, 0:43:02"
5,6,Lindsey,Lybarger,Saint Johns,FL,28,F,"1 day, 0:47:20"
6,7,Doug,Mayle,St. Petersburg,FL,56,M,"1 day, 0:59:46"
7,8,Victoria,Byrd,Miami,FL,44,F,"1 day, 1:59:00"
8,9,Stephen,Ifasi,Lutz,FL,39,M,"1 day, 2:00:00"
9,10,Sandra,Villines-Burruss,Palm City,FL,52,F,"1 day, 2:49:00"

In [14]:
data_2023.head(5)

   Place First_Name   Last_Name            City State  Age Gender      Time
0      1       Mike     Alberts       Melbourne    FL   34      M  18:33:06
1      2       Matt     Clapper             NaN   USA   41      M  19:21:53
2      3      Sarah  Raaymakers          Odessa    FL   39      F  20:43:19
3      4      Nikki   Criscuolo  South Pasadena    FL   24      F  21:02:52
4      5       Nels      Matson       Bradenton    FL   41      M  21:21:08