In [ ]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
!pip install statsmodels

Requirement already satisfied: statsmodels in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (2.4.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.17.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (3.0.0)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [ ]:
!pip install statsmodels

Requirement already satisfied: statsmodels in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (0.14.6)
Requirement already satisfied: numpy<3,>=1.22.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (2.4.2)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.17.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (3.0.0)
Requirement already satisfied: patsy>=0.5.6 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (1.0.2)
Requirement already satisfied: packaging>=21.3 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from statsmodels) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\PC\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [1]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ztest

In [8]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ztest
from scipy.stats import skew, f_oneway, pearsonr, ttest_rel,chi2_contingency, spearmanr
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
import pandas as pd
import numpy as np
from statsmodels.stats.weightstats import ztest

print("Everything imported successfully!")

Everything imported successfully!

In [6]:
import pandas as pd
print(pd.__version__)

3.0.0

In [12]:
file_path = r"C:\Users\PC\Documents\DS_Statistics_Project\Tampa 100 Video.xlsx"

data_2024 = pd.read_excel(file_path, sheet_name="2024")
data_2023 = pd.read_excel(file_path, sheet_name="2023")

In [13]:
data_2024.head(10)

,Place,First_Name,Last_Name,City,State,Age,Gender,Time
0,1,Lucas,Vidal,Cape Coral,FL,38,M,19:43:00
1,2,Brandon,Westover,Orlando,FL,45,M,21:15:00
2,3,Lucas,Hathaway,Atlanta,GA,34,M,23:31:36
3,4,Sage,Lyons,Sarasota,FL,27,F,23:37:05
4,5,Colin,Gotham,Land O Lakes,FL,30,M,"1 day, 0:43:02"
5,6,Lindsey,Lybarger,Saint Johns,FL,28,F,"1 day, 0:47:20"
6,7,Doug,Mayle,St. Petersburg,FL,56,M,"1 day, 0:59:46"
7,8,Victoria,Byrd,Miami,FL,44,F,"1 day, 1:59:00"
8,9,Stephen,Ifasi,Lutz,FL,39,M,"1 day, 2:00:00"
9,10,Sandra,Villines-Burruss,Palm City,FL,52,F,"1 day, 2:49:00"

In [14]:
data_2023.head(5)

   Place First_Name   Last_Name            City State  Age Gender      Time
0      1       Mike     Alberts       Melbourne    FL   34      M  18:33:06
1      2       Matt     Clapper             NaN   USA   41      M  19:21:53
2      3      Sarah  Raaymakers          Odessa    FL   39      F  20:43:19
3      4      Nikki   Criscuolo  South Pasadena    FL   24      F  21:02:52
4      5       Nels      Matson       Bradenton    FL   41      M  21:21:08

In [15]:
data_2024['full_name']=data_2024['First_Name'] +' '+ data_2024['Last_Name']

In [16]:
data_2023['full_name']=data_2023['First_Name'] +' '+ data_2023['Last_Name']

In [17]:
data_2024.head(10)

,Place,First_Name,Last_Name,City,State,Age,Gender,Time,full_name
0,1,Lucas,Vidal,Cape Coral,FL,38,M,19:43:00,Lucas Vidal
1,2,Brandon,Westover,Orlando,FL,45,M,21:15:00,Brandon Westover
2,3,Lucas,Hathaway,Atlanta,GA,34,M,23:31:36,Lucas Hathaway
3,4,Sage,Lyons,Sarasota,FL,27,F,23:37:05,Sage Lyons
4,5,Colin,Gotham,Land O Lakes,FL,30,M,"1 day, 0:43:02",Colin Gotham
5,6,Lindsey,Lybarger,Saint Johns,FL,28,F,"1 day, 0:47:20",Lindsey Lybarger
6,7,Doug,Mayle,St. Petersburg,FL,56,M,"1 day, 0:59:46",Doug Mayle
7,8,Victoria,Byrd,Miami,FL,44,F,"1 day, 1:59:00",Victoria Byrd
8,9,Stephen,Ifasi,Lutz,FL,39,M,"1 day, 2:00:00",Stephen Ifasi
9,10,Sandra,Villines-Burruss,Palm City,FL,52,F,"1 day, 2:49:00",Sandra Villines-Burruss

In [18]:
data_2023.head(10)

,Place,First_Name,Last_Name,City,State,Age,Gender,Time,full_name
0,1,Mike,Alberts,Melbourne,FL,34,M,18:33:06,Mike Alberts
1,2,Matt,Clapper,NaN,USA,41,M,19:21:53,Matt Clapper
2,3,Sarah,Raaymakers,Odessa,FL,39,F,20:43:19,Sarah Raaymakers
3,4,Nikki,Criscuolo,South Pasadena,FL,24,F,21:02:52,Nikki Criscuolo
4,5,Nels,Matson,Bradenton,FL,41,M,21:21:08,Nels Matson
5,6,Joe,Tumminia,Odessa,FL,57,M,22:14:05,Joe Tumminia
6,7,Tylor,Bates,Sarasota,FL,36,M,22:34:35,Tylor Bates
7,8,Nicholas,Ureña,Odessa,FL,42,M,23:06:24,Nicholas Ureña
8,9,David,Paske,Los angeles,CA,50,M,"1 day, 0:52:00",David Paske
9,10,Walter,Watts,Tampa,FL,43,M,"1 day, 1:10:00",Walter Watts

In [19]:
data_2024.drop(['First_Name','Last_Name'],axis=1,inplace=True)

In [20]:
data_2023.drop(['First_Name','Last_Name'],axis=1,inplace=True)

In [21]:
data_2024.head(5)

   Place          City State  Age Gender            Time         full_name
0      1    Cape Coral    FL   38      M        19:43:00       Lucas Vidal
1      2       Orlando    FL   45      M        21:15:00  Brandon Westover
2      3       Atlanta    GA   34      M        23:31:36    Lucas Hathaway
3      4      Sarasota    FL   27      F        23:37:05        Sage Lyons
4      5  Land O Lakes    FL   30      M  1 day, 0:43:02      Colin Gotham

In [22]:
data_2023[data_2023['Time']=='Did Not Finish'].head(5)

    Place              City State  Age Gender            Time        full_name
48      0       Brooksville    FL   62      M  Did Not Finish     Andy Mathews
49      0            Odessa    FL   61      F  Did Not Finish      Pam Dickens
50      0  New Smyrna Beach    FL   61      M  Did Not Finish   Chris Goodreau
51      0       Brooksville    FL   55      F  Did Not Finish       Laura Cole
52      0             Tampa    FL   81      M  Did Not Finish  Haywood Crowder

In [23]:
data_2024_finishers = data_2024[data_2024['Time'] !='Did Not Finish'].copy()

In [24]:
data_2023_dnf = data_2023[data_2023['Time']=='Did Not Finish'].copy()

In [25]:
data_2024_dnf = data_2024[data_2024['Time']=='Did Not Finish'].copy()

In [26]:
data_2023_dnf.drop(['Time','full_name'],axis=1,inplace=True)

In [27]:
data_2024_dnf.drop(['Time','full_name'],axis=1,inplace=True)

In [28]:
data_2023_finishers = data_2023[data_2023['Time'] !='Did Not Finish'].copy()
data_2023_finishers['Time'] = data_2023_finishers['Time'].astype(str)

In [29]:
data_2024_finishers['Time']=data_2024_finishers['Time'].astype(str)

In [30]:
data_2023_finishers['Time_Delta'] = pd.to_timedelta(data_2023_finishers['Time'])

In [31]:
data_2024_finishers['Time_Delta'] = pd.to_timedelta(data_2024_finishers['Time'])